name: avelio_sdk
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0-268.18.beta <3.0.0'


dependencies:
  protobuf: ^2.0.0
  ffi: ^1.1.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
